name:                purs-utils
version:             0.1.0.0
github:              "srghma/purs-utils"
license:             BSD3
author:              "Serhii Khoma"
maintainer:          "srghma@gmail.com"
copyright:           "2019 srghma"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/srghma/purs-utils#readme>

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveLift
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - ViewPatterns
  - DerivingStrategies
  - BlockArguments

dependencies:
  - base >= 4.7 && < 5
  - turtle
  - protolude
  - directory
  - filepath
  - text
  - foldl
  - directory-tree
  - cases
  - optparse-applicative
  - containers
  - string-qq
  - hspec
  - hspec-discover
  - regex-base
  - regex-pcre
  - regex-with-pcre
  - regex
  - async
  # - system-filepath
  - ilist
  - mtl
  - non-empty-text
  - scss-format
  - megaparsec
  # - ansi-terminal
  - safe-coloured-text
  - safe-coloured-text-terminfo
  - safe-coloured-text-layout

library:
  source-dirs: src

executables:
  purs-tidy-module-name:
    main:                Main.hs
    source-dirs:         tidy-module-name
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - purs-utils

  purs-generate-css-modules:
    main:                Main.hs
    source-dirs:         generate-css-modules
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - purs-utils

tests:
  purs-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - purs-utils
